
#include <iostream>
#include <SDL_image.h>
#include <string>

#include <FrostEngine.hpp>
#include <GridNodeDistributor.hpp>
#include <InputHandler.hpp>
#include <UIIntVariable.hpp>
#include <UIFloatVariable.hpp>
#include <UISimulationContainers.hpp>
#include <UISimulationTools.hpp>


class Simulator : public FrostEngine
{

public:

    Simulator() 
    {
        // Create UI elements
        m_grid_width_UI = UIIntVariable(&m_coh, &m_cursor_color, 
            "Grid Width", "6");
        m_grid_height_UI = UIIntVariable(&m_coh, &m_cursor_color, 
            "Grid Height", "6");
        m_chunk_width_UI = UIIntVariable(&m_coh, &m_cursor_color, 
            "Chunk Width", "3");
        m_chunk_height_UI = UIIntVariable(&m_coh, &m_cursor_color, 
            "Chunk Height", "3");
        m_nodes_per_chunk_UI = UIIntVariable(&m_coh, &m_cursor_color, 
            "Nodes per Chunk", "1");
        m_extra_node_chance_UI = UIIntVariable(&m_coh, &m_cursor_color, 
            "Extra Node Chance", "20");
        m_extra_node_threshold_UI = UIIntVariable(&m_coh, &m_cursor_color, 
            "Extra Node Threshold", "1");

        m_panel = UIPanelContainer(&m_coh, &m_cursor_color);

        m_panel.content.push_back(&m_grid_width_UI);
        m_panel.content.push_back(&m_grid_height_UI);
        m_panel.content.push_back(&m_chunk_width_UI);
        m_panel.content.push_back(&m_chunk_height_UI);
        m_panel.content.push_back(&m_nodes_per_chunk_UI);
        m_panel.content.push_back(&m_extra_node_chance_UI);
        m_panel.content.push_back(&m_extra_node_threshold_UI);

        _generate_new_grid();
    }


private:

    // Members

    uint32_t m_grid_width;
    uint32_t m_grid_height;
    uint32_t m_chunk_width;
    uint32_t m_chunk_height;
    uint32_t m_nodes_per_chunk;
    uint8_t m_extra_node_chance;
    uint32_t m_extra_node_threshold;

    SDL_Rect m_grid_src_dim;
    SDL_Rect m_grid_dest_dim;

    std::string m_cursor_color = "Blue";

    GridNodeDistributor m_node_dist;

    SDL_Texture* m_grid_texture;

    // - UI Elements - 

    UIIntVariable m_grid_width_UI;    
    UIIntVariable m_grid_height_UI;    
    UIIntVariable m_chunk_width_UI;    
    UIIntVariable m_chunk_height_UI;    
    UIIntVariable m_nodes_per_chunk_UI;    
    UIIntVariable m_extra_node_chance_UI;    
    UIIntVariable m_extra_node_threshold_UI;
    
    UIPanelContainer m_panel;


    // Methods

    void _user_update() final
    {
        if(InputHandler::is_key_pressed_and_available(SDLK_SPACE))
        {
            _generate_new_grid();
            InputHandler::block_key_until_released(SDLK_SPACE);
        }

        m_draw_handler.draw(m_grid_texture, m_grid_src_dim, m_grid_dest_dim);

        m_coh.set_cursor_x(50);
        m_coh.set_anchor(50);

        Frost::simulate_UI_panel(m_panel);
    }

    void _fetch_data_from_UI()
    {
        m_grid_width = std::stoi(m_grid_width_UI.content);
        m_grid_height = std::stoi(m_grid_height_UI.content);
        m_chunk_width = std::stoi(m_chunk_width_UI.content);
        m_chunk_height = std::stoi(m_chunk_height_UI.content);
        m_nodes_per_chunk = std::stoi(m_nodes_per_chunk_UI.content);
        m_extra_node_chance = std::stoi(m_extra_node_chance_UI.content);
        m_extra_node_threshold = std::stoi(m_extra_node_threshold_UI.content);
    }

    void _configure_texture_dimensions()
    {
        m_grid_src_dim.x = 0;
        m_grid_src_dim.y = 0;
        m_grid_src_dim.w = m_grid_width;
        m_grid_src_dim.h = m_grid_height;

        int tex_scaling_factor = get_screen_height() / (m_grid_height * 2);

        m_grid_dest_dim.x = 10;
        m_grid_dest_dim.y = 10;
        m_grid_dest_dim.w = m_grid_width * tex_scaling_factor;
        m_grid_dest_dim.h = m_grid_height * tex_scaling_factor;
    }

    void _generate_new_grid()
    {
        _fetch_data_from_UI();

        if(m_grid_texture) SDL_DestroyTexture(m_grid_texture);

        SDL_Surface* grid_surface = SDL_CreateRGBSurfaceWithFormat(0, 
            m_grid_width, m_grid_height, 32, SDL_PIXELFORMAT_RGBA32);

        uint32_t* surface_pixels = 
            static_cast<uint32_t*>(grid_surface->pixels);

        bool surface_is_locked = false;

        if(SDL_MUSTLOCK(grid_surface))
        {
            SDL_LockSurface(grid_surface);
            surface_is_locked = true;
        }

        // Fill surface with black pixels.
        for(uint32_t i = 0; i < m_grid_width * m_grid_height; ++i)
        {
            surface_pixels[i] = SDL_MapRGBA(grid_surface->format, 0, 0, 0, 
                255);
        }

        // Iterate through each node generated by the node generator.
        for(const Point2D& node : m_node_dist.get_single_value_node_distribution(
            m_grid_width, m_grid_height, m_chunk_width, m_chunk_height,
            m_nodes_per_chunk, m_extra_node_chance, m_extra_node_threshold))
        {
            surface_pixels[(node.y * m_grid_width) + node.x] = 
                SDL_MapRGBA(grid_surface->format, 250, 250, 250, 255);
        }

        if(surface_is_locked)
        {
            SDL_UnlockSurface(grid_surface);
        }

        m_grid_texture = SDL_CreateTextureFromSurface(_get_renderer(), 
            grid_surface);

        IMG_SavePNG(grid_surface, "Grid.png");

        SDL_FreeSurface(grid_surface);

        _configure_texture_dimensions();
    }
};


int main()
{
    Simulator sim;
    sim.start();

    return 0;
}